005 return the band level name with list of competencies
laura-puckoriute/ea-agile-sprint-api pull request #10
Opened 2022-10-05 08:23 UTC by yanjundev

2022-10-05 12:39 UTC, shaunganley requested changes
really good work, just 1 small comment

2022-10-05 12:39 UTC, shaunganley commented on src/main/java/org/kainos/ea/service/CompetencyService.java
> +        response.setBandLevel( bandLevelData.getBandLevelName( databaseConnector.getConnection(), id ) );
couldn't you get the band level in the getCompetenciesByBandLevel query rather than having to do multiple db requests?

2022-10-06 09:27 UTC, shaunganley requested changes

2022-10-06 09:27 UTC, shaunganley commented on src/main/java/org/kainos/ea/data/BandLevelData.java
> +public class BandLevelData {
can you delete this class now?

2022-10-06 13:47 UTC, shaunganley approved these changes

2022-10-06 13:53 UTC, laura-puckoriute approved these changes

2022-10-06 13:54 UTC, merged