040 login system
laura-puckoriute/ea-agile-sprint-api pull request #14
Opened 2022-10-10 08:15 UTC by yanjundev

2022-10-10 14:00 UTC, shaunganley requested changes
great work on this, few small comments

2022-10-10 14:00 UTC, shaunganley commented on src/main/java/org/kainos/ea/models/UserResponse.java
> +                         @JsonProperty("password") String password ) {
not sure you should have a password in a response object as you'll never return it from the API?

2022-10-10 14:00 UTC, shaunganley commented on src/main/java/org/kainos/ea/resources/AuthenticationService.java
> +    public Response removeUserToken( String token ) {
usually you wouldn't need a token to be able to sign out

2022-10-10 14:00 UTC, shaunganley commented on src/main/java/org/kainos/ea/service/UserService.java
> +            if ( token != null ) {
should there be an else statement if this is null?

2022-10-10 14:57 UTC, yanjundev commented on src/main/java/org/kainos/ea/models/UserResponse.java
> +                         @JsonProperty("password") String password ) {
that's my bad naming sense

2022-10-11 08:16 UTC, yanjundev commented on src/main/java/org/kainos/ea/resources/AuthenticationService.java
> +    public Response removeUserToken( String token ) {
changed sending token in body to "Authorization" header

2022-10-11 12:47 UTC, shaunganley approved these changes

2022-10-11 13:46 UTC, matthewknox99 approved these changes

2022-10-11 13:55 UTC, merged