015 edit role
laura-puckoriute/ea-agile-sprint-api pull request #17
Opened 2022-10-12 11:10 UTC by yanjundev

2022-10-12 12:57 UTC, BlaNaoZ approved these changes

2022-10-13 13:54 UTC, laura-puckoriute commented on src/test/java/org/kainos/ea/service/JobRolesDataTest.java
> +        Assertions.assertEquals( "role has been updated", result );
shouldn't the name of the function be updateJobRole_shouldReturnRoleHasBeenUpdated_whenJobRoleInsertSuccessful() ?

2022-10-13 13:59 UTC, laura-puckoriute requested changes

2022-10-13 13:59 UTC, laura-puckoriute commented on src/test/java/org/kainos/ea/validator/JobRoleRequestValidatorTest.java
> +
there are no tests to check the invalid lengths of **job title, link, responsibilities and requirements** fields

2023-04-04 12:41 UTC, closed without merging