Added us002 API.
laura-puckoriute/ea-agile-sprint-api pull request #6
Opened 2022-09-29 11:16 UTC by BlaNaoZ

2022-09-29 13:20 UTC, shaunganley requested changes
great work, 2 small comments

2022-09-29 13:20 UTC, shaunganley commented on src/main/java/org/kainos/ea/models/JobSpecificationResponse.java
> +    public boolean equals(Object o) {
do you need these overridden methods?

2022-09-29 13:20 UTC, shaunganley commented on src/main/java/org/kainos/ea/resources/WebService.java
> +            if(jobSpecification.getTitle() == null) {
can you move this logic to the service and unit test (you'll need to throw an exception which you can catch below)

2022-09-29 13:45 UTC, BlaNaoZ commented on src/main/java/org/kainos/ea/models/JobSpecificationResponse.java
> +    public boolean equals(Object o) {
I'm using the equals method for testing (asserting whether two responses have the same data). The hashCode one is indeed redundant, so I'll remove it.

Edit: Removed the hashCode method.

2022-09-29 15:47 UTC, BlaNaoZ commented on src/main/java/org/kainos/ea/resources/WebService.java
> +            if(jobSpecification.getTitle() == null) {
I Implemented this.

2022-09-30 13:50 UTC, shaunganley approved these changes

2022-09-30 14:13 UTC, laura-puckoriute approved these changes

2022-09-30 14:19 UTC, merged