added enviornment variable instructions in the read me file
laura-puckoriute/ea-agile-sprint-api pull request #9
Opened 2022-10-03 11:08 UTC by matthewknox99

2022-10-03 11:24 UTC, BlaNaoZ approved these changes

2022-10-04 09:58 UTC, shaunganley requested changes
can you add steps on how to run unit & integration tests please?

2022-10-04 10:29 UTC, shaunganley requested changes

2022-10-04 10:29 UTC, shaunganley commented on README.md
> +1. To run class unit/integration tests simply navigate to the test file you want to run and click on the green arrow beside the class name
give steps on how to run from the command line, not from the file, same for below

2022-10-04 12:40 UTC, shaunganley approved these changes

2022-10-04 12:48 UTC, merged